version: "3.7"

services:
    nginx:
        image: laravel-nginx
        build:
            context: .
            dockerfile: docker/nginx.Dockerfile
        env_file:
            - .env
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./:/var/www
        links:
            - fpm
        restart: always
        depends_on:
            - fpm
            - websockets
    fpm:
        image: laravel-fpm
        build:
            context: .
            dockerfile: docker/fpm.Dockerfile
        env_file:
            - .env
        volumes:
            - ./:/var/www
        ports:
            - "9000"
            - "${VITE_PORT}:${VITE_PORT}"
        links:
            - db
            - redis
            - websockets
        restart: always
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_started
    queue:
        image: laravel-fpm
        container_name: queue
        command: php artisan queue:work
        links:
            - db
            - redis
            - websockets
        restart: always
        volumes:
            - .:/var/www
    schedule:
        image: laravel-fpm
        container_name: schedule
        command: php artisan schedule:work
        links:
            - db
            - redis
            - websockets
        restart: always
        volumes:
            - .:/var/www
    websockets:
        image: laravel-fpm
        container_name: websockets
        command: php artisan websockets:serve
        links:
            - db
            - redis
        ports:
            - "6001"
        restart: always
        volumes:
            - .:/var/www
    db:
        image: mysql:5.7
        ports:
            - "${FORWARD_DB_PORT:-DB_PORT}:${DB_PORT}"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        restart: always
        healthcheck:
            test: "exit 0"
    redis:
        image: redis:alpine
        ports:
            - "${FORWARD_REDIS_PORT:-REDIS_PORT}:${REDIS_PORT}"
        restart: always

