version: "3.7"

services:
    nginx:
        image: laravel-nginx
        build:
            context: .
            dockerfile: docker/nginx.Dockerfile
        env_file:
            - .env
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./:/var/www/app
        links:
            - fpm
        restart: always
        depends_on:
            - fpm
    fpm:
        image: laravel-fpm
        build:
            context: .
            dockerfile: docker/fpm.Dockerfile
        env_file:
            - .env
        volumes:
            - ./:/var/www/app
        ports:
            - "9000"
            - "6001"
            - "${VITE_PORT}:${VITE_PORT}"
        links:
            - db
            - redis
        restart: always
        depends_on:
            - db
            - redis
    db:
        image: mysql:5.7
        ports:
            - "${FORWARD_DB_PORT:-DB_PORT}:${DB_PORT}"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        restart: always
    redis:
        image: laravel-redis
        build:
            context: .
            dockerfile: docker/redis.Dockerfile
        env_file:
            - .env
        ports:
            - "${FORWARD_REDIS_PORT:-REDIS_PORT}:${REDIS_PORT}"
        restart: always

